import React from 'react'
import Head from 'next/head'

export type AppHeaderProps = {
  title?: string;
  children?: React.ReactNode;
}

const AppHeader = (props: AppHeaderProps) => {
  const { title, children } = props;
  return (
    <Head>
      <title>{title + ' | Next.js App'}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      {children}
    </Head>
  )
}

AppHeader.defaultProps = {
  title: 'Home',
}

export default AppHeader